/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cloud-ark/kubeplus/platform-operator/pkg/apis/workflowcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeResourceMonitors implements ResourceMonitorInterface
type FakeResourceMonitors struct {
	Fake *FakeWorkflowsV1alpha1
	ns   string
}

var resourcemonitorsResource = schema.GroupVersionResource{Group: "workflows.kubeplus", Version: "v1alpha1", Resource: "resourcemonitors"}

var resourcemonitorsKind = schema.GroupVersionKind{Group: "workflows.kubeplus", Version: "v1alpha1", Kind: "ResourceMonitor"}

// Get takes name of the resourceMonitor, and returns the corresponding resourceMonitor object, and an error if there is any.
func (c *FakeResourceMonitors) Get(name string, options v1.GetOptions) (result *v1alpha1.ResourceMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(resourcemonitorsResource, c.ns, name), &v1alpha1.ResourceMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceMonitor), err
}

// List takes label and field selectors, and returns the list of ResourceMonitors that match those selectors.
func (c *FakeResourceMonitors) List(opts v1.ListOptions) (result *v1alpha1.ResourceMonitorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(resourcemonitorsResource, resourcemonitorsKind, c.ns, opts), &v1alpha1.ResourceMonitorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ResourceMonitorList{ListMeta: obj.(*v1alpha1.ResourceMonitorList).ListMeta}
	for _, item := range obj.(*v1alpha1.ResourceMonitorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested resourceMonitors.
func (c *FakeResourceMonitors) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(resourcemonitorsResource, c.ns, opts))

}

// Create takes the representation of a resourceMonitor and creates it.  Returns the server's representation of the resourceMonitor, and an error, if there is any.
func (c *FakeResourceMonitors) Create(resourceMonitor *v1alpha1.ResourceMonitor) (result *v1alpha1.ResourceMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(resourcemonitorsResource, c.ns, resourceMonitor), &v1alpha1.ResourceMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceMonitor), err
}

// Update takes the representation of a resourceMonitor and updates it. Returns the server's representation of the resourceMonitor, and an error, if there is any.
func (c *FakeResourceMonitors) Update(resourceMonitor *v1alpha1.ResourceMonitor) (result *v1alpha1.ResourceMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(resourcemonitorsResource, c.ns, resourceMonitor), &v1alpha1.ResourceMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceMonitor), err
}

// Delete takes name of the resourceMonitor and deletes it. Returns an error if one occurs.
func (c *FakeResourceMonitors) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(resourcemonitorsResource, c.ns, name), &v1alpha1.ResourceMonitor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeResourceMonitors) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(resourcemonitorsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ResourceMonitorList{})
	return err
}

// Patch applies the patch and returns the patched resourceMonitor.
func (c *FakeResourceMonitors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourceMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(resourcemonitorsResource, c.ns, name, data, subresources...), &v1alpha1.ResourceMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceMonitor), err
}
