/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cloud-ark/kubeplus/platform-operator/pkg/apis/workflowcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeResourceCompositions implements ResourceCompositionInterface
type FakeResourceCompositions struct {
	Fake *FakeWorkflowsV1alpha1
	ns   string
}

var resourcecompositionsResource = schema.GroupVersionResource{Group: "workflows.kubeplus", Version: "v1alpha1", Resource: "resourcecompositions"}

var resourcecompositionsKind = schema.GroupVersionKind{Group: "workflows.kubeplus", Version: "v1alpha1", Kind: "ResourceComposition"}

// Get takes name of the resourceComposition, and returns the corresponding resourceComposition object, and an error if there is any.
func (c *FakeResourceCompositions) Get(name string, options v1.GetOptions) (result *v1alpha1.ResourceComposition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(resourcecompositionsResource, c.ns, name), &v1alpha1.ResourceComposition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceComposition), err
}

// List takes label and field selectors, and returns the list of ResourceCompositions that match those selectors.
func (c *FakeResourceCompositions) List(opts v1.ListOptions) (result *v1alpha1.ResourceCompositionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(resourcecompositionsResource, resourcecompositionsKind, c.ns, opts), &v1alpha1.ResourceCompositionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ResourceCompositionList{ListMeta: obj.(*v1alpha1.ResourceCompositionList).ListMeta}
	for _, item := range obj.(*v1alpha1.ResourceCompositionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested resourceCompositions.
func (c *FakeResourceCompositions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(resourcecompositionsResource, c.ns, opts))

}

// Create takes the representation of a resourceComposition and creates it.  Returns the server's representation of the resourceComposition, and an error, if there is any.
func (c *FakeResourceCompositions) Create(resourceComposition *v1alpha1.ResourceComposition) (result *v1alpha1.ResourceComposition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(resourcecompositionsResource, c.ns, resourceComposition), &v1alpha1.ResourceComposition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceComposition), err
}

// Update takes the representation of a resourceComposition and updates it. Returns the server's representation of the resourceComposition, and an error, if there is any.
func (c *FakeResourceCompositions) Update(resourceComposition *v1alpha1.ResourceComposition) (result *v1alpha1.ResourceComposition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(resourcecompositionsResource, c.ns, resourceComposition), &v1alpha1.ResourceComposition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceComposition), err
}

// Delete takes name of the resourceComposition and deletes it. Returns an error if one occurs.
func (c *FakeResourceCompositions) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(resourcecompositionsResource, c.ns, name), &v1alpha1.ResourceComposition{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeResourceCompositions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(resourcecompositionsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ResourceCompositionList{})
	return err
}

// Patch applies the patch and returns the patched resourceComposition.
func (c *FakeResourceCompositions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourceComposition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(resourcecompositionsResource, c.ns, name, data, subresources...), &v1alpha1.ResourceComposition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceComposition), err
}
