apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resourceevents.workflows.kubeplus
spec:
  group: workflows.kubeplus
  version: v1alpha1
  names:
    kind: ResourceEvent
    plural: resourceevents
  scope: Namespaced

