# Sized to work on 3 k8s workers nodes with 1 core / 4 GB RAM
# See neighboring example-cassdc-full.yaml for docs for each parameter
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc3
  annotations:
    function-AddLabel: "Fn::AddLabel(application/dc3, CassandraDatacenter:default.dc2:PodDisruptionBudget)"
    function-AddAnnotation: "Fn::AddAnnotation(application/dc3, CassandraDatacenter:default.dc2:PodDisruptionBudget)"
spec:
  clusterName: cluster3
  serverType: dse
  serverVersion: "6.8.1"
  managementApiAuth:
    insecure: {}
  size: 1 
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: server-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  config:
    jvm-server-options:
      initial_heap_size: "800M"
      max_heap_size: "800M"
