FROM ubuntu:20.04 
RUN arch=$(arch | sed s/aarch64/arm64/ | sed s/x86_64/amd64/) && cd /root/ && curl -LO "https://dl.k8s.io/release/v1.26.0/bin/linux/${arch}/kubectl"
COPY waiter.sh /root/
RUN chmod +x /root/kubectl && chmod +x /root/waiter.sh
ENTRYPOINT ["/root/waiter.sh"]
