#!/bin/bash

if (( $# < 2 )); then
    echo "kubectl crlogs <Custom Resource> <Resource Instance> [<Namespace>]"
    exit 0
fi

namespace="default"

# If namespace is passed; use that
if [ $# = 3 ]; then
   namespace=$3
fi

#echo "Custom Resource: $1"
#echo "Custom Resource Instance: $2"
#echo "Namespace: $namespace"
#echo "======================"
podlist=(`kubectl get --raw "/apis/platform-as-code/v1/composition?kind=$1&instance=$2&namespace=$namespace" | python -m json.tool | grep -B 1 -A 4 Pod | grep Name | grep -v Namespace | awk '{print $2}' | sed 's/"//'g | sed 's/,//'g`)
#echo "Pod:$pod"
#echo "PodList: $podlist"

if [ ${#podlist[@]} -eq 0 ];
then
	echo "No Pod found for Custom Resource $1 named $2 in Namespace $namespace."
else
        #echo "Pods for Custom Resource $1 named $2 in Namespace $namespace."
        #for i in "${podlist[@]}"; do echo "$i"; done
        for p in "${podlist[@]}"; do
            python crlogs.py $p $namespace
        done;
fi
