#!/bin/bash

#echo "You provided $# arguments"

#for arg in "$@"
#do
#    echo "$arg"
#done

if (( $# < 1 )); then
    echo "kubectl metrics account <Account name>"
    exit 0
fi

account=$1

python crmetrics.py $account

#echo "Custom Resource: $1"
#echo "Custom Resource Instance: $2"
#echo "Namespace: $namespace"
#echo "======================"
#podlist=(`kubectl get --raw "/apis/platform-as-code/v1/composition?kind=$1&instance=$2&namespace=$namespace" | python -m json.tool | grep -B 1 -A 4 Pod | grep Name | grep -v Namespace | awk '{print $2}' | sed 's/"//'g | sed 's/,//'g`)
#echo "Pod:$pod"
#echo "PodList: $podlist"

#if [ -z "$pod" ]
#if [ ${#podlist[@]} -eq 0 ];
#then
#	echo "No Pod found for Custom Resource $1 named $2 in Namespace $namespace."
#else
#        echo "Pods for Custom Resource $1 named $2 in Namespace $namespace."
#        for i in "${podlist[@]}"; do echo "$i"; done
#        echo "NAME               CPU(cores)   MEMORY(bytes)"
#        for p in "${podlist[@]}"; do
#            kubectl top pods "$p" --namespace=$namespace | grep -v NAME
#        done;
#fi