#!/bin/bash

#echo "You provided $# arguments"

#for arg in "$@"
#do
#    echo "$arg"
#done

if (( $# < 2 )); then
    echo "kubectl tree <Custom Resource> <Custom Resource Instance> [<Namespace>]"
    exit 0
fi

namespace="default"

# If namespace is passed; use that
if [ $# = 3 ]; then
   namespace=$3
fi

#echo "Custom Resource: $1"
#echo "Custom Resource Instance: $2"
#echo "Namespace: $namespace"
#echo "======================"
kubectl get --raw "/apis/platform-as-code/v1/composition?kind=$1&instance=$2&namespace=$namespace" | python -m json.tool
