#!/bin/bash

#echo "You provided $# arguments"

#for arg in "$@"
#do
#    echo "$arg"
#done

if (( $# < 2 )); then
    echo "kubectl metrics <Custom Resource> <Custom Resource Instance> [<Namespace>]"
    exit 0
fi

namespace="default"

# If namespace is passed; use that
if [ $# = 3 ]; then
   namespace=$3
fi

#echo "Custom Resource: $1"
#echo "Custom Resource Instance: $2"
#echo "Namespace: $namespace"
#echo "======================"
pod=`kubectl get --raw "/apis/platform-as-code/v1/composition?kind=$1&instance=$2&namespace=$namespace" | python -m json.tool | grep -B 1 -A 4 Pod | grep Name | grep -v Namespace | awk '{print $2}' | sed 's/"//'g | sed 's/,//'g`
#echo "Pod:$pod"
if [ -z "$pod" ]
then
	echo "No Pod found for Custom Resource $1 in Namespace $namespace"
else
	kubectl top pods $pod --namespace=$namespace
fi