/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cloud-ark/kubeplus/platform-operator/pkg/apis/workflowcontroller/v1alpha1"
	scheme "github.com/cloud-ark/kubeplus/platform-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PlatformWorkflowsGetter has a method to return a PlatformWorkflowInterface.
// A group's client should implement this interface.
type PlatformWorkflowsGetter interface {
	PlatformWorkflows(namespace string) PlatformWorkflowInterface
}

// PlatformWorkflowInterface has methods to work with PlatformWorkflow resources.
type PlatformWorkflowInterface interface {
	Create(*v1alpha1.PlatformWorkflow) (*v1alpha1.PlatformWorkflow, error)
	Update(*v1alpha1.PlatformWorkflow) (*v1alpha1.PlatformWorkflow, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PlatformWorkflow, error)
	List(opts v1.ListOptions) (*v1alpha1.PlatformWorkflowList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PlatformWorkflow, err error)
	PlatformWorkflowExpansion
}

// platformWorkflows implements PlatformWorkflowInterface
type platformWorkflows struct {
	client rest.Interface
	ns     string
}

// newPlatformWorkflows returns a PlatformWorkflows
func newPlatformWorkflows(c *WorkflowsV1alpha1Client, namespace string) *platformWorkflows {
	return &platformWorkflows{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the platformWorkflow, and returns the corresponding platformWorkflow object, and an error if there is any.
func (c *platformWorkflows) Get(name string, options v1.GetOptions) (result *v1alpha1.PlatformWorkflow, err error) {
	result = &v1alpha1.PlatformWorkflow{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("platformworkflows").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PlatformWorkflows that match those selectors.
func (c *platformWorkflows) List(opts v1.ListOptions) (result *v1alpha1.PlatformWorkflowList, err error) {
	result = &v1alpha1.PlatformWorkflowList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("platformworkflows").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested platformWorkflows.
func (c *platformWorkflows) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("platformworkflows").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a platformWorkflow and creates it.  Returns the server's representation of the platformWorkflow, and an error, if there is any.
func (c *platformWorkflows) Create(platformWorkflow *v1alpha1.PlatformWorkflow) (result *v1alpha1.PlatformWorkflow, err error) {
	result = &v1alpha1.PlatformWorkflow{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("platformworkflows").
		Body(platformWorkflow).
		Do().
		Into(result)
	return
}

// Update takes the representation of a platformWorkflow and updates it. Returns the server's representation of the platformWorkflow, and an error, if there is any.
func (c *platformWorkflows) Update(platformWorkflow *v1alpha1.PlatformWorkflow) (result *v1alpha1.PlatformWorkflow, err error) {
	result = &v1alpha1.PlatformWorkflow{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("platformworkflows").
		Name(platformWorkflow.Name).
		Body(platformWorkflow).
		Do().
		Into(result)
	return
}

// Delete takes name of the platformWorkflow and deletes it. Returns an error if one occurs.
func (c *platformWorkflows) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("platformworkflows").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *platformWorkflows) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("platformworkflows").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched platformWorkflow.
func (c *platformWorkflows) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PlatformWorkflow, err error) {
	result = &v1alpha1.PlatformWorkflow{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("platformworkflows").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
