/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cloud-ark/kubeplus/platform-operator/pkg/apis/workflowcontroller/v1alpha1"
	scheme "github.com/cloud-ark/kubeplus/platform-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ResourceMonitorsGetter has a method to return a ResourceMonitorInterface.
// A group's client should implement this interface.
type ResourceMonitorsGetter interface {
	ResourceMonitors(namespace string) ResourceMonitorInterface
}

// ResourceMonitorInterface has methods to work with ResourceMonitor resources.
type ResourceMonitorInterface interface {
	Create(*v1alpha1.ResourceMonitor) (*v1alpha1.ResourceMonitor, error)
	Update(*v1alpha1.ResourceMonitor) (*v1alpha1.ResourceMonitor, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ResourceMonitor, error)
	List(opts v1.ListOptions) (*v1alpha1.ResourceMonitorList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourceMonitor, err error)
	ResourceMonitorExpansion
}

// resourceMonitors implements ResourceMonitorInterface
type resourceMonitors struct {
	client rest.Interface
	ns     string
}

// newResourceMonitors returns a ResourceMonitors
func newResourceMonitors(c *WorkflowsV1alpha1Client, namespace string) *resourceMonitors {
	return &resourceMonitors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the resourceMonitor, and returns the corresponding resourceMonitor object, and an error if there is any.
func (c *resourceMonitors) Get(name string, options v1.GetOptions) (result *v1alpha1.ResourceMonitor, err error) {
	result = &v1alpha1.ResourceMonitor{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcemonitors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResourceMonitors that match those selectors.
func (c *resourceMonitors) List(opts v1.ListOptions) (result *v1alpha1.ResourceMonitorList, err error) {
	result = &v1alpha1.ResourceMonitorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcemonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested resourceMonitors.
func (c *resourceMonitors) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("resourcemonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a resourceMonitor and creates it.  Returns the server's representation of the resourceMonitor, and an error, if there is any.
func (c *resourceMonitors) Create(resourceMonitor *v1alpha1.ResourceMonitor) (result *v1alpha1.ResourceMonitor, err error) {
	result = &v1alpha1.ResourceMonitor{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("resourcemonitors").
		Body(resourceMonitor).
		Do().
		Into(result)
	return
}

// Update takes the representation of a resourceMonitor and updates it. Returns the server's representation of the resourceMonitor, and an error, if there is any.
func (c *resourceMonitors) Update(resourceMonitor *v1alpha1.ResourceMonitor) (result *v1alpha1.ResourceMonitor, err error) {
	result = &v1alpha1.ResourceMonitor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resourcemonitors").
		Name(resourceMonitor.Name).
		Body(resourceMonitor).
		Do().
		Into(result)
	return
}

// Delete takes name of the resourceMonitor and deletes it. Returns an error if one occurs.
func (c *resourceMonitors) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcemonitors").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *resourceMonitors) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcemonitors").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched resourceMonitor.
func (c *resourceMonitors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourceMonitor, err error) {
	result = &v1alpha1.ResourceMonitor{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("resourcemonitors").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
