/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cloud-ark/kubeplus/platform-operator/pkg/apis/workflowcontroller/v1alpha1"
	scheme "github.com/cloud-ark/kubeplus/platform-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ResourcePoliciesGetter has a method to return a ResourcePolicyInterface.
// A group's client should implement this interface.
type ResourcePoliciesGetter interface {
	ResourcePolicies(namespace string) ResourcePolicyInterface
}

// ResourcePolicyInterface has methods to work with ResourcePolicy resources.
type ResourcePolicyInterface interface {
	Create(*v1alpha1.ResourcePolicy) (*v1alpha1.ResourcePolicy, error)
	Update(*v1alpha1.ResourcePolicy) (*v1alpha1.ResourcePolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ResourcePolicy, error)
	List(opts v1.ListOptions) (*v1alpha1.ResourcePolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourcePolicy, err error)
	ResourcePolicyExpansion
}

// resourcePolicies implements ResourcePolicyInterface
type resourcePolicies struct {
	client rest.Interface
	ns     string
}

// newResourcePolicies returns a ResourcePolicies
func newResourcePolicies(c *WorkflowsV1alpha1Client, namespace string) *resourcePolicies {
	return &resourcePolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the resourcePolicy, and returns the corresponding resourcePolicy object, and an error if there is any.
func (c *resourcePolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.ResourcePolicy, err error) {
	result = &v1alpha1.ResourcePolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcepolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResourcePolicies that match those selectors.
func (c *resourcePolicies) List(opts v1.ListOptions) (result *v1alpha1.ResourcePolicyList, err error) {
	result = &v1alpha1.ResourcePolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested resourcePolicies.
func (c *resourcePolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("resourcepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a resourcePolicy and creates it.  Returns the server's representation of the resourcePolicy, and an error, if there is any.
func (c *resourcePolicies) Create(resourcePolicy *v1alpha1.ResourcePolicy) (result *v1alpha1.ResourcePolicy, err error) {
	result = &v1alpha1.ResourcePolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("resourcepolicies").
		Body(resourcePolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a resourcePolicy and updates it. Returns the server's representation of the resourcePolicy, and an error, if there is any.
func (c *resourcePolicies) Update(resourcePolicy *v1alpha1.ResourcePolicy) (result *v1alpha1.ResourcePolicy, err error) {
	result = &v1alpha1.ResourcePolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resourcepolicies").
		Name(resourcePolicy.Name).
		Body(resourcePolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the resourcePolicy and deletes it. Returns an error if one occurs.
func (c *resourcePolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcepolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *resourcePolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcepolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched resourcePolicy.
func (c *resourcePolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourcePolicy, err error) {
	result = &v1alpha1.ResourcePolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("resourcepolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
