/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cloud-ark/kubeplus/platform-operator/pkg/apis/workflowcontroller/v1alpha1"
	scheme "github.com/cloud-ark/kubeplus/platform-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ResourceCompositionsGetter has a method to return a ResourceCompositionInterface.
// A group's client should implement this interface.
type ResourceCompositionsGetter interface {
	ResourceCompositions(namespace string) ResourceCompositionInterface
}

// ResourceCompositionInterface has methods to work with ResourceComposition resources.
type ResourceCompositionInterface interface {
	Create(*v1alpha1.ResourceComposition) (*v1alpha1.ResourceComposition, error)
	Update(*v1alpha1.ResourceComposition) (*v1alpha1.ResourceComposition, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ResourceComposition, error)
	List(opts v1.ListOptions) (*v1alpha1.ResourceCompositionList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourceComposition, err error)
	ResourceCompositionExpansion
}

// resourceCompositions implements ResourceCompositionInterface
type resourceCompositions struct {
	client rest.Interface
	ns     string
}

// newResourceCompositions returns a ResourceCompositions
func newResourceCompositions(c *WorkflowsV1alpha1Client, namespace string) *resourceCompositions {
	return &resourceCompositions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the resourceComposition, and returns the corresponding resourceComposition object, and an error if there is any.
func (c *resourceCompositions) Get(name string, options v1.GetOptions) (result *v1alpha1.ResourceComposition, err error) {
	result = &v1alpha1.ResourceComposition{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcecompositions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResourceCompositions that match those selectors.
func (c *resourceCompositions) List(opts v1.ListOptions) (result *v1alpha1.ResourceCompositionList, err error) {
	result = &v1alpha1.ResourceCompositionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcecompositions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested resourceCompositions.
func (c *resourceCompositions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("resourcecompositions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a resourceComposition and creates it.  Returns the server's representation of the resourceComposition, and an error, if there is any.
func (c *resourceCompositions) Create(resourceComposition *v1alpha1.ResourceComposition) (result *v1alpha1.ResourceComposition, err error) {
	result = &v1alpha1.ResourceComposition{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("resourcecompositions").
		Body(resourceComposition).
		Do().
		Into(result)
	return
}

// Update takes the representation of a resourceComposition and updates it. Returns the server's representation of the resourceComposition, and an error, if there is any.
func (c *resourceCompositions) Update(resourceComposition *v1alpha1.ResourceComposition) (result *v1alpha1.ResourceComposition, err error) {
	result = &v1alpha1.ResourceComposition{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resourcecompositions").
		Name(resourceComposition.Name).
		Body(resourceComposition).
		Do().
		Into(result)
	return
}

// Delete takes name of the resourceComposition and deletes it. Returns an error if one occurs.
func (c *resourceCompositions) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcecompositions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *resourceCompositions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcecompositions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched resourceComposition.
func (c *resourceCompositions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourceComposition, err error) {
	result = &v1alpha1.ResourceComposition{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("resourcecompositions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
