/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cloud-ark/kubeplus/platform-operator/pkg/apis/workflowcontroller/v1alpha1"
	scheme "github.com/cloud-ark/kubeplus/platform-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ResourceEventsGetter has a method to return a ResourceEventInterface.
// A group's client should implement this interface.
type ResourceEventsGetter interface {
	ResourceEvents(namespace string) ResourceEventInterface
}

// ResourceEventInterface has methods to work with ResourceEvent resources.
type ResourceEventInterface interface {
	Create(*v1alpha1.ResourceEvent) (*v1alpha1.ResourceEvent, error)
	Update(*v1alpha1.ResourceEvent) (*v1alpha1.ResourceEvent, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ResourceEvent, error)
	List(opts v1.ListOptions) (*v1alpha1.ResourceEventList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourceEvent, err error)
	ResourceEventExpansion
}

// resourceEvents implements ResourceEventInterface
type resourceEvents struct {
	client rest.Interface
	ns     string
}

// newResourceEvents returns a ResourceEvents
func newResourceEvents(c *WorkflowsV1alpha1Client, namespace string) *resourceEvents {
	return &resourceEvents{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the resourceEvent, and returns the corresponding resourceEvent object, and an error if there is any.
func (c *resourceEvents) Get(name string, options v1.GetOptions) (result *v1alpha1.ResourceEvent, err error) {
	result = &v1alpha1.ResourceEvent{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourceevents").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResourceEvents that match those selectors.
func (c *resourceEvents) List(opts v1.ListOptions) (result *v1alpha1.ResourceEventList, err error) {
	result = &v1alpha1.ResourceEventList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourceevents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested resourceEvents.
func (c *resourceEvents) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("resourceevents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a resourceEvent and creates it.  Returns the server's representation of the resourceEvent, and an error, if there is any.
func (c *resourceEvents) Create(resourceEvent *v1alpha1.ResourceEvent) (result *v1alpha1.ResourceEvent, err error) {
	result = &v1alpha1.ResourceEvent{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("resourceevents").
		Body(resourceEvent).
		Do().
		Into(result)
	return
}

// Update takes the representation of a resourceEvent and updates it. Returns the server's representation of the resourceEvent, and an error, if there is any.
func (c *resourceEvents) Update(resourceEvent *v1alpha1.ResourceEvent) (result *v1alpha1.ResourceEvent, err error) {
	result = &v1alpha1.ResourceEvent{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resourceevents").
		Name(resourceEvent.Name).
		Body(resourceEvent).
		Do().
		Into(result)
	return
}

// Delete takes name of the resourceEvent and deletes it. Returns an error if one occurs.
func (c *resourceEvents) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourceevents").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *resourceEvents) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourceevents").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched resourceEvent.
func (c *resourceEvents) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourceEvent, err error) {
	result = &v1alpha1.ResourceEvent{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("resourceevents").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
