#!/bin/bash

if (( $# < 2 )); then
    echo "kubectl metrics cr <Custom Resource> <Resource Instance> [<Namespace>]"
    exit 0
fi

customres=$1
instance=$2
namespace="default"

# If namespace is passed; use that
if [ $# = 3 ]; then
   namespace=$3
fi

python ./plugins/crmetrics.py $customres $instance $namespace
