#!/bin/bash

if (( $# < 2 )); then
    echo "kubectl composition <Custom Resource Kind> <Custom Resource Instance> [<Namespace>]"
    exit 0
fi

namespace="default"

# If namespace is passed; use that
if [ $# = 3 ]; then
   namespace=$3
fi

kind=$1
instance=$2

if [[ "$OSTYPE" == "darwin"* ]]; then
    /$KUBEPLUS_HOME/plugins/kubediscovery-macos composition $kind $instance $namespace
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    /$KUBEPLUS_HOME/plugins/kubediscovery-linux composition $kind $instance $namespace
else
        echo "$OSTYPE not supported."
fi
