#!/bin/bash

source utils.sh

print_help () {
    echo "NAME"
    echo "        kubectl retrieve kubeconfig consumer"
    echo ""
    echo "SYNOPSIS"
    echo "        kubectl retrieve kubeconfig consumer [-s <api server url>] [-k <kubeconfig path>]"
    echo ""
    echo "DESCRIPTION"
    echo "        This command is used to retrieve consumer kubeconfig file."
    echo "        -s <api server url> is an optional argument to pass the URL of the API server. "
    echo "        This URL will be embedded in the generated kubeconfig for the server endpoint." 
    echo "        -k is an optional argument to pass the kubeconfig that needs to be used to access the cluster."
    exit 0
}

kubeconfig="$HOME/.kube/config" #default value
serverURL='-1'

#echo $@
while getopts ":k:s:" opt; do
  case ${opt} in
    k )
	  #echo "A:${OPTARG}"
      kubeconfig=${OPTARG}
      if [ ! -f $kubeconfig ]; then
        echo "Kubeconfig $kubeconfig does not exist."
        exit 0
      fi
      ;;
    s )
      #echo "B:${OPTARG}"
	  serverURL=${OPTARG}
	  ;;
  esac
done

python /$KUBEPLUS_HOME/plugins/kubeconfigretriever.py $serverURL "consumer" $kubeconfig

