#!/bin/bash

function podLogs {
	podlist=("$@")
	echo "===Pods==="
    for i in "${podlist[@]}"; do echo "$i"; done
	echo "   "
	if [ ${#podlist[@]} -eq 0 ];
	then
		echo "No Pod found for Workflow from Service $serviceInstance in Namespace $namespace."
	else
        for p in "${podlist[@]}"; do
            python ./plugins/crlogs.py $p $namespace
        done;
	fi
}

if (( $# < 1 )); then
    echo "kubectl grouplogs workflow Service <Service Instance name> [<Namespace>]"
    exit 0
fi

serviceInstance=$2
namespace="default"
if [ $# = 3 ]; then
   namespace=$3 # If namespace is passed; use that
fi

IFS=$'\n' # field separator: '\n'
declare -a podlist
if [[ "$OSTYPE" == "darwin"* ]]; then
	podlist=( $(./plugins/kubediscovery-macos connections Service $serviceInstance $namespace | grep Pod | awk '{print $3}' | cut -d ':' -f2) )
	podLogs "${podlist[@]}"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
	podlist=( $(./plugins/kubediscovery-linux connections Service $serviceInstance $namespace | grep Pod | awk '{print $3}' | cut -d ':' -f2) )
	podLogs "${podlist[@]}"
else 
	echo "$OSTYPE not supported."
fi
