#!/bin/bash

echo "Upcoming..."
exit 0

if (( $# < 1 )); then
    echo "kubectl connections workflow <PlatformWorkflow Instance name> [<Namespace>]"
    exit 0
fi

instance=$1
namespace="default"
if [ $# = 2 ]; then
   namespace=$2 # If namespace is passed; use that
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
	/$KUBEPLUS_HOME/plugins/kubediscovery-macos connections PlatformWorkflow $instance $namespace
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
	/$KUBEPLUS_HOME/plugins/kubediscovery-linux connections PlatformWorkflow $instance $namespace
else
	echo "$OSTYPE not supported."
fi
