#!/bin/bash

if (( $# < 1 )); then
    echo "kubectl connections service <Service Instance name> [<Namespace>]"
    exit 0
fi

serviceInstance=$1
namespace="default"
if [ $# = 2 ]; then
   namespace=$2 # If namespace is passed; use that
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
	/$KUBEPLUS_HOME/plugins/kubediscovery-macos connections Service $serviceInstance $namespace -o flat
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
	/$KUBEPLUS_HOME/plugins/kubediscovery-linux connections Service $serviceInstance $namespace -o flat
else
	echo "$OSTYPE not supported."
fi
