#!/bin/bash

print_help () {
    echo "NAME"
    echo "        kubectl kubeplus commands"
    echo ""
    echo "SYNOPSIS"
    echo "        kubectl man"
    echo "        kubectl connections"
    echo "        kubectl metrics"
    echo "        kubectl grouplogs"
    echo ""
    echo "DESCRIPTION"
    echo "        KubePlus provides a suite of kubectl plugins to discover, monitor and troubleshoot Kubernetes application stacks."
    echo "        An application stack is identified in four different ways in KubePlus:"
    echo "        - Helm release: An application stack can be all the resources that are part of a Helm release."
    echo "        - Kubernetes Custom Resource: An application stack can be all the resources that are connected through various relationships "
    echo "          to the input Custom resource."
    echo "        - Kubernetes Service: An application stack can be all the resources that are reachable through various relationships"
    echo "           from the input Service instance."
    echo "        - Account: An application stack can be all the resources that are created by a particular 'account'."
    echo ""
    echo "        The discovery plugins (kubectl man and kubectl connections) help with discovering the static and runtime information about an application stack."
    echo "        - kubectl man provides the ability for Operator developers to publish any information that is needed by the consumers of their Custom Resources."
    echo "        - kubectl connections provides the ability to discover Kubernetes resources that are related to one another through following relationships - "
    echo "           ownerReferences, label, annotations, spec properties."
    echo "        The monitoring and troubleshooting plugins (kubectl metrics and kubectl grouplogs) provide sub-commands that work with"
    echo "        different definitions of application stacks identified above. Run them without any parameters to find out about the sub-commands."
    echo "        kubectl metrics and kubectl grouplogs use kubectl connections for application stack discovery."
    exit 0
}

print_help
