#!/bin/bash

if (( $# < 3 )); then
    echo "kubectl metrics cr <Custom Resource Kind> <Resource Instance> <Namespace> [-o json]"
    exit 0
fi

customres=$1
instance=$2
namespace="$3"

output="pretty"
if [ $# == 5 ]; then
   output=$5
fi

#echo $output

python /$KUBEPLUS_HOME/plugins/crmetrics.py "cr" $customres $instance $namespace $output
