#!/bin/bash

print_help () {
    echo "NAME"
    echo "        kubectl grouplogs"
    echo ""
    echo "SYNOPSIS"
    echo "        kubectl grouplogs <Kind> <Instance> <Namespace> [--kubeconfig=<Absolute path to kubeconfig>]"
    echo ""
    echo "DESCRIPTION"
    echo "        kubectl grouplogs shows container logs for all the containers that are related to the input Kubernetes resource."
    echo "        It take three inputs - the name of the Kubernetes Resource/Kind, the name of the instance of that Kind and the Namespace name."
    exit 0
}

if (( $# < 3 )); then
  print_help
fi

kind=$1
instance=$2
namespace=$3

# Only --kubeconfig specified
kubeconfig='--kubeconfig="$HOME/.kube/config"'
if [ $# = 4 ] && [[ $4 == *"kubeconfig="* ]]; then
    kubeconfig=$4
fi

#echo "$kind $instance $namespace"

python /$KUBEPLUS_HOME/plugins/crlogs.py connections $kind $instance $namespace $kubeconfig


#echo "kubectl grouplogs cr connections"
#echo "kubectl grouplogs service"
#echo "kubectl grouplogs helmrelease"
