#!/bin/bash

#python3 crlicense.py delete "$@"

source utils.sh

print_help () {
    echo "NAME"
    echo "        kubectl license delete"
    echo ""
    echo "SYNOPSIS"
    echo "        kubectl license delete <Kind> -k <Full path to kubeconfig file>"
    echo ""
    echo "DESCRIPTION"
    echo "        kubectl license delete deletes the license registered for the Kind."
    exit 0
}

if (( $# < 3 )); then
  print_help
fi

kind=$1
shift;

while getopts ":k:h" opt; do
  case ${opt} in
    k )
      kubeconfig=$OPTARG
      if [ ! -f $kubeconfig ]; then
        echo "Kubeconfig $kubeconfig does not exist."
        exit 0
      fi;;
    h ) print_help;;
    ? )
      echo "Invalid option: ${1} " 1>&2
      print_help
      exit 0
      ;;
  esac
done

check_kind $kind $kubeconfig

lowercase_kind=`echo "$kind" | tr '[:upper:]' '[:lower:]'`
kubeplus_ns=`get_kubeplus_ns $kubeconfig`
kubectl delete configmap $lowercase_kind-license -n $kubeplus_ns --kubeconfig=$kubeconfig &> /dev/null

if [[ $? == 0 ]]; then
	echo "License for Kind $kind deleted."
else
	echo "License for Kind $kind not found."
fi



