#!/bin/bash

if (( $# < 2 )); then
    echo "kubectl grantpermission consumer <resourceplural>  <providerKubeconfig>"
    exit 0
fi

kubeplusNS=$3
resPlural=$1
providerKubeconfig=$2

pythonPath=`which python3`
if [[ $? == 0 ]]; then
	`$pythonPath /$KUBEPLUS_HOME/plugins/consumerkubeconfigretriever.py $resPlural $providerKubeconfig`
	echo "Consumer granted permission on $resPlural."
else
	echo "Encountered error in granting permission to consumer on $resPlural"
fi
