#!/bin/bash

if (( $# < 1 )); then
    echo "kubectl retrieve kubeconfig consumer <Namespace in which KubePlus is deployed>" #<resourceplural> <providerKubeconfig>"
    exit 0
fi

kubeplusNS=$1

#resPlural=$2
#providerKubeconfig=$3
#pythonPath=`which python`
#if [[ $? == 0 ]]; then
#	`$pythonPath /$KUBEPLUS_HOME/plugins/consumerkubeconfigretriever.py $kubeplusNS $resPlural $providerKubeconfig`
#fi

kubectl get configmaps kubeplus-saas-consumer-kubeconfig -n $kubeplusNS -o jsonpath="{.data.kubeplus-saas-consumer\.json}"
