#!/bin/bash

if (( $# < 1 )); then
    echo "kubectl retrieve kubeconfig provider <Namespace in which KubePlus is deployed>"
    exit 0
fi

kubeplusNS=$1
kubectl get configmaps kubeplus-saas-provider-kubeconfig -n $kubeplusNS -o jsonpath="{.data.kubeplus-saas-provider\.json}"
