#!/bin/bash

if (( $# < 1 )); then
    echo "kubectl connections workflow Service <Service Instance name> [<Namespace>]"
    exit 0
fi

serviceInstance=$2
namespace="default"
if [ $# = 3 ]; then
   namespace=$3 # If namespace is passed; use that
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
	./plugins/kubediscovery-macos connections Service $serviceInstance $namespace
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
	./plugins/kubediscovery-linux connections Service $serviceInstance $namespace
else
	echo "$OSTYPE not supported."
fi
