#!/bin/bash

if (( $# < 1 )); then
    echo "kubectl metrics service <Service Instance name> [<Namespace>]"
    exit 0
fi

serviceinstance=$1
namespace="default"

# If namespace is passed; use that                                                                                             
if [ $# = 2 ]; then
   namespace=$2
fi

#echo "Namespace:$namespace"
#echo "ServiceInstance:$serviceinstance"

python /$KUBEPLUS_HOME/plugins/crmetrics.py service $serviceinstance $namespace
