#!/bin/bash

if (( $# < 2 )); then
    echo "kubectl composition <Kind> <Instance> <Namespace> [--kubeconfig=<Absolute path to kubeconfig>]"
    exit 0
fi

kind=$1
instance=$2
namespace=$3

if [ $# = 4 ] && [[ $4 == *"kubeconfig="* ]]; then
	kubeconfig=$4
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
    /$KUBEPLUS_HOME/plugins/kubediscovery-macos composition $kind $instance $namespace $kubeconfig
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    /$KUBEPLUS_HOME/plugins/kubediscovery-linux composition $kind $instance $namespace $kubeconfig
else
        echo "$OSTYPE not supported."
fi
