#!/bin/bash

# kubectl man uses the default kubeconfig. Do we need to support passing
# in a custom kubeconfig file? For now, we will skip this.

source utils.sh

if (( $# < 1 )); then
    echo "kubectl man <Custom Resource Kind>"
    exit 0
fi

kind=$1

kubeconfig1="$HOME/.kube/config" #default value

kubeconfig="--kubeconfig="$kubeconfig1

check_kind $kind $kubeconfig

if [[ "$OSTYPE" == "darwin"* ]]; then
	/$KUBEPLUS_HOME/plugins/kubediscovery-macos man $kind
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
	/$KUBEPLUS_HOME/plugins/kubediscovery-linux man $kind
else 
	echo "$OSTYPE not supported."
fi


