#!/bin/bash

source utils.sh

print_help () {
    echo "NAME"
    echo "        kubectl license get"
    echo ""
    echo "SYNOPSIS"
    echo "        kubectl license get <Kind> -k <Full path to kubeconfig file>"
    echo ""
    echo "DESCRIPTION"
    echo "        kubectl license get retrieves the license registered for the Kind."
    exit 0
}

if (( $# < 1 )); then
  print_help
fi

kind=$1
shift;

while getopts ":k:h" opt; do
  case ${opt} in
    k )
      kubeconfig=$OPTARG
      if [ ! -f $kubeconfig ]; then
        echo "Kubeconfig $kubeconfig does not exist."
        exit 0
      fi;;
    h ) print_help;;
    ? )
      echo "Invalid option: ${1} " 1>&2
      print_help
      exit 0
      ;;
  esac
done


check_kind $kind $kubeconfig

lowercase_kind=`echo "$kind" | tr '[:upper:]' '[:lower:]'`
kubeplus_ns=`get_kubeplus_ns $kubeconfig`
op=`kubectl get configmaps $lowercase_kind-license -o custom-columns=EXPIRY:.metadata.annotations.expiry,ALLOWED_INSTANCES:.metadata.annotations.allowed_instances,LICENSE_FILE:.data.license_file 2> /dev/null`

if [[ $? == 0 ]]; then
	echo "$op"
else
        echo "License for Kind $kind not found."
fi




