#!/bin/bash

function podLogs {
	podlist=("$@")
	echo "===Pods==="
        for i in "${podlist[@]}"; do echo "$i"; done
	echo "   "
	if [ ${#podlist[@]} -eq 0 ];
	then
		echo "No Pod found associated with Service $serviceInstance in Namespace $namespace."
	else
        for p in "${podlist[@]}"; do
            python /$KUBEPLUS_HOME/plugins/crlogs.py $p $namespace
        done;
	fi
}

if (( $# < 1 )); then
    echo "kubectl grouplogs service <Service Instance name> [<Namespace>]"
    exit 0
fi

serviceInstance=$1
namespace="default"
if [ $# = 2 ]; then
   namespace=$2 # If namespace is passed; use that
fi

IFS=$'\n' # field separator: '\n'
declare -a podlist
if [[ "$OSTYPE" == "darwin"* ]]; then
	#podlist=( $($KUBEPLUS_HOME/plugins/kubediscovery-macos connections Service $serviceInstance $namespace -o flat | grep Pod | awk '{print $3}' | cut -d ':' -f2) )
	#podLogs "${podlist[@]}"
	service_output=$($KUBEPLUS_HOME/plugins/kubediscovery-macos connections Service $serviceInstance $namespace -o json)
    python /$KUBEPLUS_HOME/plugins/crlogs.py $service_output $namespace
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
	#podlist=( $($KUBEPLUS_HOME/plugins/kubediscovery-linux connections Service $serviceInstance $namespace -o flat | grep Pod | awk '{print $3}' | cut -d ':' -f2) )
	#podLogs "${podlist[@]}"
	service_output=$($KUBEPLUS_HOME/plugins/kubediscovery-linux connections Service $serviceInstance $namespace -o json)
    python /$KUBEPLUS_HOME/plugins/crlogs.py $service_output $namespace
else 
	echo "$OSTYPE not supported."
fi
