#!/bin/bash

print_help () {
    echo "NAME"
    echo "        kubectl kubeplus commands"
    echo ""
    echo "SYNOPSIS"
    echo "        kubectl man"
    echo "        kubectl connections"
    echo "        kubectl metrics"
    echo "        kubectl applogs"
    echo ""
    echo "DESCRIPTION"
    echo "        KubePlus provides a suite of kubectl plugins to discover, monitor and troubleshoot Kubernetes applications."
    echo ""
    echo "        The discovery plugins (kubectl man and kubectl connections) help with discovering the static and runtime"
    echo "        information about an application."
    echo "        - kubectl man provides the ability to discover man page like information about Kubernetes Custom Resources."
    echo "        - kubectl connections provides the ability to discover Kubernetes resources that are related to one another"
    echo "          through one of the following relationships - ownerReferences, label, annotations, spec properties."
    echo "        The monitoring and troubleshooting plugins (kubectl metrics and kubectl applogs) enable collecting application metrics and logs."
    echo "        - kubectl metrics collects CPU, Memory, Storage, and Network metrics for an application. These are available in Prometheus format."
    echo "        - kubectl applogs collects logs for all the containers of all the Pods in an application."
    exit 0
}

print_help
