FROM ubuntu:20.04
ADD delete-kubeplus-components.sh /root/.
COPY kubectl /root/
RUN apt-get update && apt-get install -y openssl jq python3 python3-pip && pip3 install pyyaml
RUN cp /root/kubectl bin/. && chmod +x /root/kubectl && chmod +x bin/kubectl 
ENTRYPOINT ["/root/delete-kubeplus-components.sh"]
