FROM ubuntu:20.04
RUN apt-get update && apt-get install -y openssl jq python3 python3-pip && pip3 install pyyaml
COPY kubectl /root/
COPY kubeconfiggenerator.py /root/.
COPY kubeconfiggenerator.sh /root/.
RUN cp /root/kubectl bin/. && chmod +x /root/kubectl && chmod +x bin/kubectl && chmod +x /root/kubeconfiggenerator.sh
ENTRYPOINT ["/root/kubeconfiggenerator.sh"]
