apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeplus-mcp
  namespace: kagent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeplus-mcp
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - persistentvolumeclaims
      - resourcequotas
      - namespaces
      - configmaps
      - secrets
    verbs:
      - get
      - list

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs:
      - get
      - list

  - apiGroups: [""]
    resources:
      - replicationcontrollers
    verbs:
      - get
      - list

  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs:
      - get
      - list

  - apiGroups: ["platformapi.kubeplus"]
    resources:
      - "*"
    verbs:
      - get
      - list

  - apiGroups: ["workflows.kubeplus"]
    resources:
      - resourcecompositions
      - resourcemonitors
    verbs:
      - get
      - list

  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeplus-mcp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeplus-mcp
subjects:
  - kind: ServiceAccount
    name: kubeplus-mcp
    namespace: kagent
