apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wordpress-tenants
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: default
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinationServiceAccounts:
    - server: https://kubernetes.default.svc
      namespace: default
      defaultServiceAccount: kubeplus-saas-consumer
