apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeplus-wordpress-tenants
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_WITH_GIT_REPO_URL
    targetRevision: REPLACE_WITH_GIT_TARGET_REVISION
    path: examples/multitenancy/application-hosting/wordpress-argocd/tenants
  destination:
    server: https://kubernetes.default.svc
    namespace: REPLACE_WITH_KUBEPLUS_NAMESPACE
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
