/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	platformstackcontrollerv1 "github.com/cloud-ark/kubeplus/platform-operator/pkg/apis/platformstackcontroller/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePlatformStacks implements PlatformStackInterface
type FakePlatformStacks struct {
	Fake *FakePlatformstackV1
	ns   string
}

var platformstacksResource = schema.GroupVersionResource{Group: "platformstack.kubeplus", Version: "v1", Resource: "platformstacks"}

var platformstacksKind = schema.GroupVersionKind{Group: "platformstack.kubeplus", Version: "v1", Kind: "PlatformStack"}

// Get takes name of the platformStack, and returns the corresponding platformStack object, and an error if there is any.
func (c *FakePlatformStacks) Get(name string, options v1.GetOptions) (result *platformstackcontrollerv1.PlatformStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(platformstacksResource, c.ns, name), &platformstackcontrollerv1.PlatformStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*platformstackcontrollerv1.PlatformStack), err
}

// List takes label and field selectors, and returns the list of PlatformStacks that match those selectors.
func (c *FakePlatformStacks) List(opts v1.ListOptions) (result *platformstackcontrollerv1.PlatformStackList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(platformstacksResource, platformstacksKind, c.ns, opts), &platformstackcontrollerv1.PlatformStackList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &platformstackcontrollerv1.PlatformStackList{ListMeta: obj.(*platformstackcontrollerv1.PlatformStackList).ListMeta}
	for _, item := range obj.(*platformstackcontrollerv1.PlatformStackList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested platformStacks.
func (c *FakePlatformStacks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(platformstacksResource, c.ns, opts))

}

// Create takes the representation of a platformStack and creates it.  Returns the server's representation of the platformStack, and an error, if there is any.
func (c *FakePlatformStacks) Create(platformStack *platformstackcontrollerv1.PlatformStack) (result *platformstackcontrollerv1.PlatformStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(platformstacksResource, c.ns, platformStack), &platformstackcontrollerv1.PlatformStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*platformstackcontrollerv1.PlatformStack), err
}

// Update takes the representation of a platformStack and updates it. Returns the server's representation of the platformStack, and an error, if there is any.
func (c *FakePlatformStacks) Update(platformStack *platformstackcontrollerv1.PlatformStack) (result *platformstackcontrollerv1.PlatformStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(platformstacksResource, c.ns, platformStack), &platformstackcontrollerv1.PlatformStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*platformstackcontrollerv1.PlatformStack), err
}

// Delete takes name of the platformStack and deletes it. Returns an error if one occurs.
func (c *FakePlatformStacks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(platformstacksResource, c.ns, name), &platformstackcontrollerv1.PlatformStack{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePlatformStacks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(platformstacksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &platformstackcontrollerv1.PlatformStackList{})
	return err
}

// Patch applies the patch and returns the patched platformStack.
func (c *FakePlatformStacks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *platformstackcontrollerv1.PlatformStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(platformstacksResource, c.ns, name, pt, data, subresources...), &platformstackcontrollerv1.PlatformStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*platformstackcontrollerv1.PlatformStack), err
}
