apiVersion: workflows.kubeplus/v1alpha1
kind: ResourceComposition
metadata:
  name: helloappv2-composition
spec:
  # newResource defines the new CRD to be installed define a workflow.
  newResource:
    resource:
      kind: HelloAppV2
      group: platformapi.kubeplus
      version: v1alpha1
      plural: helloappv2s 
    # URL of the Helm chart that contains Kubernetes resources that represent a workflow.
    chartURL: file:///helloappv2-chart-0.0.1.tgz
    chartName: helloappv2-chart 
  # respolicy defines the resource policy to be applied to instances of the specified custom resource.
  respolicy:
    apiVersion: workflows.kubeplus/v1alpha1
    kind: ResourcePolicy 
    metadata:
      name: helloappv2-policy
    spec:
      resource:
        kind: HelloAppV2 
        group: platformapi.kubeplus
        version: v1alpha1
  # resmonitor identifies the resource instances that should be monitored for CPU/Memory/Storage.
  # All the Pods that are related to the resource instance through either ownerReference relationship, or all the relationships
  # (ownerReference, label, annotation, spec properties) are considered in calculating the statistics. 
  # The generated output is in Prometheus format.
  resmonitor:
    apiVersion: workflows.kubeplus/v1alpha1
    kind: ResourceMonitor
    metadata:
      name: helloappv2-monitor
    spec:
      resource:
        kind: HelloAppV2 
        group: platformapi.kubeplus
        version: v1alpha1
      # This attribute indicates that Pods that are reachable through all the relationships should be used
      # as part of calculating the monitoring statistics.
      monitorRelationships: all
