/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	workflowcontrollerv1alpha1 "github.com/cloud-ark/kubeplus/platform-operator/pkg/apis/workflowcontroller/v1alpha1"
	versioned "github.com/cloud-ark/kubeplus/platform-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/cloud-ark/kubeplus/platform-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/cloud-ark/kubeplus/platform-operator/pkg/client/listers/workflowcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ResourceEventInformer provides access to a shared informer and lister for
// ResourceEvents.
type ResourceEventInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ResourceEventLister
}

type resourceEventInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewResourceEventInformer constructs a new informer for ResourceEvent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewResourceEventInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredResourceEventInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredResourceEventInformer constructs a new informer for ResourceEvent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredResourceEventInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkflowsV1alpha1().ResourceEvents(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkflowsV1alpha1().ResourceEvents(namespace).Watch(options)
			},
		},
		&workflowcontrollerv1alpha1.ResourceEvent{},
		resyncPeriod,
		indexers,
	)
}

func (f *resourceEventInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredResourceEventInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *resourceEventInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&workflowcontrollerv1alpha1.ResourceEvent{}, f.defaultInformer)
}

func (f *resourceEventInformer) Lister() v1alpha1.ResourceEventLister {
	return v1alpha1.NewResourceEventLister(f.Informer().GetIndexer())
}
